version: '3.8'

services:
  api:
    build: ./api
    container_name: actix_api
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  app:
    build: ./app
    container_name: nuxt_app
    ports:
      - "3000:3000"
    depends_on:
      - api

  mongo:
    image: mongo:latest
    container_name: mongo_db
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: